# Generated by Django 5.2.6 on 2026-04-13 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commentlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
