# Generated by Django 5.2.6 on 2026-04-11 06:38

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='answers_images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='question_images/'),
        ),
    ]
