# Generated by Django 5.2.6 on 2026-03-04 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Upload the Techlife-bd Logo', upload_to='footer/')),
                ('description', models.TextField(help_text="The short 'About Us' text in the footer")),
                ('email', models.EmailField(default='contact@techlife.com', max_length=254)),
                ('phone', models.CharField(default='+8801700895489', max_length=20)),
                ('address', models.TextField(default='Green Road, Dhaka')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook profile link', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile link', null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile link', null=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number with country code', max_length=20, null=True)),
                ('developer_company_name', models.CharField(default='Intelligent Systems & Solution Limited', max_length=100)),
                ('developer_company_url', models.URLField(default='#')),
            ],
            options={
                'verbose_name': 'Footer Setting',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='contact_or_support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
