# Generated by Django 5.2.6 on 2026-04-11 06:38

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(help_text='Upload the Techlife-bd Logo', upload_to='footer/'),
        ),
    ]
