# Generated by Django 5.2.6 on 2026-03-04 05:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ad_code', ckeditor.fields.RichTextField()),
                ('order', models.PositiveIntegerField(choices=[(1, 'After Hero Section'), (2, 'After Blog Grid'), (3, 'After Latest News'), (4, 'After Particular Category'), (5, 'After Most View'), (6, 'After Marquee'), (7, 'Popular sidebar'), (8, 'Category Details page'), (9, 'Under Top question (hero section)')], help_text='Select which section this ad should appear after', unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['order'],
            },
        ),
    ]
