# Generated by Django 5.2.6 on 2026-03-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_add', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='order',
            field=models.PositiveIntegerField(choices=[(1, 'After Hero Section'), (2, 'After Blog Grid'), (3, 'After Latest News'), (4, 'After Particular Category'), (5, 'After Most View'), (6, 'After Marquee'), (7, 'Popular sidebar'), (8, 'Category Details page'), (9, 'Under Top question (hero section)'), (10, 'Category page add(left side)')], help_text='Select which section this ad should appear after', unique=True),
        ),
    ]
