# Generated by Django 5.2.6 on 2026-03-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0002_blogpost_description_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='description_hash',
        ),
    ]
