# Generated by Django 5.2.6 on 2026-04-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0002_alter_blogpost_slug_alter_blogpost_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='blog_images/'),
        ),
    ]
