# Generated by Django 5.2.6 on 2026-04-11 06:38

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0004_add_blogpost_meta_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogadditionalimage',
            name='additional_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='blog_images/additional/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, max_length=500, null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='compnay_logo',
            name='company_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='company/image'),
        ),
    ]
