# Generated by Django 5.2.6 on 2026-04-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0006_alter_blogpost_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
