# Generated by Django 5.1.8 on 2026-08-29 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0013_automationpublishlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='automationpublishlog',
            name='auth_source',
            field=models.CharField(blank=True, choices=[('automation', 'Admin Automation Token'), ('user_token', 'User Personal API Token')], db_index=True, max_length=20, null=True, verbose_name='Auth Source'),
        ),
        migrations.AddField(
            model_name='automationpublishlog',
            name='source_ip',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Source IP'),
        ),
        migrations.AddField(
            model_name='automationpublishlog',
            name='token_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='User Token ID'),
        ),
        migrations.AddField(
            model_name='automationpublishlog',
            name='token_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_token_logs', to=settings.AUTH_USER_MODEL, verbose_name='Token Owner'),
        ),
    ]
