# Generated by Django 5.2.6 on 2026-04-11 06:38

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='user_profile/default_user_profile.png', null=True, upload_to='user_profile'),
        ),
    ]
