# Generated by Django 5.1.8 on 2026-08-29 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customusermodel_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAPIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='A memorable label, e.g. "My Portfolio Site"', max_length=100, verbose_name='Token Label')),
                ('token_prefix', models.CharField(help_text='First visible chars of the token (safe to display)', max_length=24, verbose_name='Token Prefix')),
                ('hashed_token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Hashed Token (SHA-256)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for a non-expiring token', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'User API Token',
                'verbose_name_plural': 'User API Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_2f564c_idx')],
            },
        ),
    ]
