# Generated by Django 5.2.6 on 2026-03-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_under_maintenance', models.BooleanField(default=False, help_text='Activates maintenance mode across all pages.', verbose_name='Entire Website')),
                ('forum_under_maintenance', models.BooleanField(default=False, help_text='Activates maintenance mode on forum pages only.', verbose_name='Forum Section')),
                ('maintenance_until', models.DateTimeField(blank=True, help_text='Set the date and time when maintenance will end. A live countdown will display on the modal. Leave blank to hide the timer.', null=True, verbose_name='Maintenance Until')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maintenance Settings',
                'verbose_name_plural': 'Maintenance Settings',
            },
        ),
    ]
