# Generated by Django 5.2.6 on 2026-03-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics Measurement ID (e.g., G-XXXXXXXXXX)', max_length=50, null=True)),
                ('site_title', models.CharField(default='TechLife || Know The Current Situation', help_text='Website এর Main Title', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='Website এর Meta Description (160 character এর মধ্যে রাখুন)', null=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
