# Generated by Django 5.2.6 on 2026-03-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarningSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_rate', models.FloatField(default=0.01)),
                ('like_rate', models.FloatField(default=0.5)),
                ('comment_rate', models.FloatField(default=1.0)),
                ('quality_rate', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
